In [1]:
import numpy as np

Question 1

In [14]:
#Q1
A = np.array([10,11,12,13,14])
print("Initial array:",A)
D = 5
new_A = np.zeros(len(A) + (len(A)-1)*(D))
new_A[::p+1] = A
print("Final array:",new_A)

Initial array: [10 11 12 13 14]
Final array: [10.  0.  0.  0.  0.  0. 11.  0.  0.  0.  0.  0. 12.  0.  0.  0.  0.  0.
 13.  0.  0.  0.  0.  0. 14.]


Question 2

In [15]:
#Q2
A1=np.random.randint(0,100,10)
print("Array 1:",A1)
A2=np.random.randint(0,100,10)
print("Array 2:",A2)
equal=np.allclose(A1,A2)
print("Is the arrays are equal or not? :",equal)

Array 1: [ 4 55 30  5 98 19  6 61 37 83]
Array 2: [86 19  7 66 54 90 74 31 75 80]
Is the arrays are equal or not? : False


Question 3(Here nan means not a number )

In [16]:
#Q3
print(0 * np.nan)
print(np.nan != np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1) 

nan
True
False
nan
False


Question 4

In [17]:
import pandas as pd

In [38]:
#Q4
S=pd.Series(['amrita', 'school', 'of', 'engineering' ,'chennai' , 'campus'])
print(S)
new_S = S.map(lambda x: x[0].upper() + x[1:-1]+x[-1] )
print("the requires new series is :")
print(new_S)
for i in range(1,len(new_S)):
    new_S[0]=new_S[0]+' '+new_S[i]
print("the obtained new series after combining  is :",new_S[0])

0         amrita
1         school
2             of
3    engineering
4        chennai
5         campus
dtype: object
the requires new series is :
0         Amrita
1         School
2             Of
3    Engineering
4        Chennai
5         Campus
dtype: object
the obtained new series after combining  is : Amrita School Of Engineering Chennai Campus


Question 5

In [42]:
#Q5 Addition of two arrays
Arr1=np.random.randint(0,100,8)
print("array 1:")
print(Arr1)
Arr2=np.random.randint(0,10,8)
print("array 2:")
print(Arr2)
sum=np.add(Arr1,Arr2)
print("The addition of two arrays is :")
print(sum)

array 1:
[98 72 34 24  7 93 78 69]
array 2:
[0 2 9 2 3 6 4 4]
The addition of two arrays is :
[98 74 43 26 10 99 82 73]


In [45]:
#Q5 multiplication of two matrices
M1=np.random.randint(0,1000,(4,4))
print("Matrix 1:")
print(M1)
M2=np.random.randint(0,1000,(4,4))
print("Matrix 2:")
print(M2)
mult=np.dot(M1,M2)
print("the multiplication of the above two matrices is :")
print(mult)

Matrix 1:
[[362 757 484  95]
 [978 866 295 260]
 [515 552 760 404]
 [229 215 639 869]]
Matrix 2:
[[101 924 369 816]
 [812 212 662 666]
 [426 387 484 865]
 [889 451 818 480]]
the multiplication of the above two matrices is :
[[ 941885  725125  946678 1263814]
 [1158780 1318689 1289634 1754779]
 [1183155 1069208 1253771 1639192]
 [1242464  896388 1246949 1299909]]


In [47]:
#Q5 Identity matrix
I_matrix=np.identity(6)
print(I_matrix)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]
